### PR TITLE
v0.22.1

### PR DESCRIPTION
**Pull request by paulcsmith**
Updates the .crystal-version to 0.35.0

### CODE REVIEW

**Comment by jwoertink** [comment]
I have these updates in #525 I've been stuck on the specs passing.

**Comment by jwoertink** [comment]
well, I should say some of them. Looks like you have a lot more going on here.

**Comment by paulcsmith** [comment]
This is just an update to .crystal-version. The rest are there just because it is comparing to master (I can't seem to compare to a tag) :(

**Comment by paulcsmith** [comment]
Changed the base so it looks like it should!

**Pull request closed without merging**
