### PR TITLE
Rename with_defaults to tag_defaults

### LINKED ISSUE #548: Change Shared::Field to use `tag_defaults` and yield `tag_builder`
https://github.com/luckyframework/lucky/discussions/1244. Depends on https://github.com/luckyframework/lucky/issues/1252

### PR DESCRIPTION
**Pull request by stephendolan**
This PR aims to close #548

It will need to be released in conjunction with https://github.com/luckyframework/lucky/pull/1262

This PR tackles:
- Renaming with_defaults in `browser_app_skeleton/src/components/shared/field.cr` to the new `tag_defaults` signature implemented [here](https://github.com/luckyframework/lucky/pull/1262)
- Renaming the yielded block from `input_builder` to `tag_builder` to keep all Lucky-generated docs/code/comments consistent and (hopefully) better convey meaning

I wasn't sure how to get the specs passing here since the method won't be found in Lucky until a new version is available.

### CODE REVIEW

**Review by jwoertink — COMMENTED** [review]
This will be fine. Obviously we will need to update the Lucky version. To get the specs to pass, we can now update https://github.com/luckyframework/lucky_cli/blob/master/shard.override.yml to point to lucky master. Once the other PR is merged in, we can rerun specs here and they will be good.

**Comment by stephendolan** [comment]
@jwoertink Sorry, somehow I missed your comment. Do you want me to go ahead and update shard.override.yml in this PR?

**Comment by jwoertink** [comment]
@stephendolan yeah, it's a pretty common thing we end up having to do so it's fine. Update it to point to lucky master, and we will see if the specs all pass.

**Review by jwoertink — APPROVED** [review]
Looks good to me!

**Pull request merged**
