### PR TITLE
Update security_spec.cr.ecr

### PR DESCRIPTION
**Pull request by bararchy**
Added and Optimized tests.
This should only be merged once we merge https://github.com/luckyframework/lucky_sec_tester/pull/28

### CODE REVIEW

**Comment by jwoertink** [comment]
https://github.com/luckyframework/lucky_sec_tester/pull/28 was merged. 

The Ameba failure is expected, but looks like there's one other sec tester fail.

**Comment by bararchy** [comment]
@jwoertink can we pull latest SecTester and retest ?

**Comment by jwoertink** [comment]
@bararchy sure. Just add it here https://github.com/luckyframework/lucky_cli/blob/main/shard.override.yml and I think it should pull it in.

**Comment by bararchy** [comment]
@jwoertink Taking another look I think this should be fine now, can you re-run the Actions?

**Comment by bararchy** [comment]
@jwoertink I need you to re-run the tests so that it will use your API token ENV 
image

**Pull request merged**
