### PR TITLE
See if there are errors on master

### PR DESCRIPTION
**Pull request by paulcsmith**
I think the changes I made to Lucky::Params somehow messed things up and thankfully the full integration suite in this repo caught them. 

I first saw this in https://github.com/luckyframework/lucky_cli/pull/481, which I don't think has anything to do with the compile message. So testing without those changes to be sure

### CODE REVIEW

**Comment by paulcsmith** [comment]
Yep the params thing broke it. Will investigate. I think I know what change broke it, but I'm not sure why 🤔

**Comment by wontruefree** [comment]
Is this on release 0.19.0?

**Comment by paulcsmith** [comment]
@wontruefree No it is in Lucky master so 0.19 is good :)

**Comment by paulcsmith** [comment]
Here is the PR and the specific line that I think caused the issue: https://github.com/luckyframework/lucky/pull/1053/files#diff-d633a5eeaf04a8d42861bcc3614b84bfR481

**Comment by paulcsmith** [comment]
Fixed: https://github.com/luckyframework/lucky/pull/1061

**Pull request closed without merging**
