### PR TITLE
[DO NOT MERGE] v0.18.4

### PR DESCRIPTION
**Pull request by jwoertink**
Bumping version to support Crystal 0.33.0

Specs are failing both locally and in the docker container... I'm not sure why yet. Gonna see if they pass here on travis.

```
Finished in 5:04 minutes
34 examples, 8 failures, 1 errors, 0 pending

Failed examples:

crystal spec spec/integration/init_web_spec.cr:23 # Initializing a new web project creates a full web app with generator
crystal spec spec/integration/init_web_spec.cr:46 # Initializing a new web project creates an api only web app successfully
crystal spec spec/integration/init_web_spec.cr:52 # Initializing a new web project creates an api only app without auth
crystal spec spec/integration/init_web_spec.cr:58 # Initializing a new web project creates a full app without auth
crystal spec spec/integration/init_web_spec.cr:64 # Initializing a new web project does not create project if directory with same name already exist
crystal spec spec/integration/init_web_spec.cr:76 # Initializing a new web project does not create project if project name is not a valid project name
crystal spec spec/integration/task_spec.cr:8 # Running a task runs precompiled tasks
crystal spec spec/integration/task_spec.cr:16 # Running a task allows tasks to accept input from STDIN
crystal spec spec/integration/init_web_spec.cr:88 # Initializing a new web project translates dashes to underscores in the project name
```

### CODE REVIEW

**Comment by jwoertink** [comment]
Looks like specs passed on the CI which tells me that the failing stuff might be something weird with my machine. Could be cache, or the fact that catalina sucks... no clue... I'll hold off on releasing this though until I get some more eyes , or insight on this.

**Comment by paulcsmith** [comment]
@jwoertink I usually trust the CI specs over my local machine because Docker is weird and Travis starts fresh every time, but I agree better to be safe. I’ll give it a go tomorrow and let you know

Thanks for doing these updates!

**Comment by paulcsmith** [comment]
Looks like @snadon upgraded and it worked out well. I think this is good to go since it worked in prod and CI and there are very minimal changes

If we have to we can yank it but I think it’ll work

**Comment by jwoertink** [comment]
tagging and releasing this!

**Pull request closed without merging**
