### PR TITLE
Chore: dockerfile dev fixes (gunzip, bump lucky-cli)

### PR DESCRIPTION
**Pull request by stan-slas**
Hello LuckyCLI Team,

I am new to _Crystal world_ and wanted to give a try without installing various dependencies on my host (like configuring postgresql :see_no_evil: ), but current dev dockerfile generated by Lucky CLI had some issues:

| :whale: step | Command | Error | Comment |
| --- | ---  | --- | --- |
| STEP2 | `apt-get install -y wget gzip` |  `Unable to locate package gunzip` |  `gunzip` is already installed from the base image `crystal:1.4.1`. If it was missing I guess `gzip` is the package to install to get gunzip, gzip and zcat |
| STEP8 |  `git checkout v0.30.0` | N/A | Cf https://github.com/luckyframework/lucky_cli/issues/781, I was expecting to get the latest release. I just did another hardcoded bump for now |

**How it has been tested ?**
After this PR I was able to build and run the container with various lucky cli
* `lucky --version` => `1.0.0-rc1` 
* `lucky init` working too

Now I have to try the framework :smiley:

PS: maybe worth it mentioning in the doc https://luckyframework.org/guides/getting-started/installing that docker and compose templates are available ? That's a great feature !

### CODE REVIEW

**Comment by wontruefree** [comment]
I am currently working through my docker files and made these changes locally.  This is a great update.

**Review by jwoertink — APPROVED** [review]
Awesome! Thanks so much for fixing this. Welcome to Lucky :tada:

**Comment by stan-slas** [comment]
Regarding the CI I got 
```
 API token is invalid, please generate a new one response: Failed to log in with provided credentials. (SecTester::Error)
```
at each SecTester test.

I am wondering if the 
https://github.com/luckyframework/lucky_cli/blob/9dba5f7f2fd961f382706fa37fc3fb3da6006328/.github/workflows/security.yml#L66-L67

are still valid ? :thinking:

**Comment by jwoertink** [comment]
Yeah, I might just have to generate a new one, it looks like.

@bararchy do these expire normally? I haven't changed anything, so I'm not sure if this is something I have to just keep updated from time to time?

**Pull request merged**
