### PR TITLE
Generate docs for CI

### PR DESCRIPTION
**Pull request by mdwagner**
## Purpose
Generates docs (`crystal docs`) for Travis CI
Continuation of: https://github.com/luckyframework/lucky/issues/988

## Description
On any commit into `master`, this will auto-deploy documentation generated from `crystal docs` on Github Pages. **Note:** I needed to target `src/lucky_cli.cr` specifically, otherwise it fails on out-of-order requires.

**Travis CI config needs to be updated to include GITHUB_TOKEN environment variable**
The GITHUB_TOKEN, which is a [github personal access token](https://help.github.com/en/github/authenticating-to-github/creating-a-personal-access-token-for-the-command-line), only needs the `public_repo` scope.

### CODE REVIEW

**Comment by mdwagner** [comment]
@jwoertink should I also add a script for running the specs? `script/test`

**Comment by jwoertink** [comment]
@mdwagner There's already one for that https://github.com/luckyframework/lucky_cli/blob/master/script/test. Plus I think that'd be a different PR anyway. I'm just thinking since the other projects also included a `script/docs`, it's nice to stay consistent since we have a lot of repos to manage.

**Comment by mdwagner** [comment]
@jwoertink is there anything holding this up from merging?

**Comment by jwoertink** [comment]
My forgetful brain? 😂 Actually, I don't know where that `$GITHUB_TOKEN` value comes from, but I think this is all ok to merge now. I assume we can just plug that value in later if @paulcsmith has it.

**Comment by mdwagner** [comment]
@jwoertink he needs to add that token on travis, like he's done already on Lucky and Avram repos.

**Comment by jwoertink** [comment]
Cool. Yeah, I don't have access to the travis account, so we'll let Paul handle that part. Thanks for taking care of this!

**Comment by mdwagner** [comment]
No problem! happy to help :smile:

**Pull request merged**
